### ISSUE TITLE
The virustotal_json file

### ISSUE THREAD

**Issue by QiuJYWX** [alewarne/ExplainSecurityDNNs#1]
Hi alewarne,

Thanks for your time and attention. 

It seems that there lack the  virustotal_json file when training the network for Drebin dataset. 

Besides, I have downloaded the two datasets released by "https://github.com/CGCL-codes/VulDeePecker". However, it seems that there lack the code script to convert the 'cwe119_cgd.txt'  file to the json file required by the experiments 

If you can share this file and the code script, that would be highly appreciated.

Regards,
Junyang

**Comment by alewarne** [comment]
Hi,

- To get access to the Drebin dataset please use the [official website](https://www.sec.tu-bs.de/~danarp/drebin/)
- The required json file for VulDeePecker is in the zip file in the corresponding folder
